name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: 检出代码
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: 设置 SSH 私钥
      - name: Set up SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # 从 Secrets 中读取私钥
          SSH_HOST: ${{ secrets.SSH_HOST }}               # 在 Secrets 中设置的服务器 IP 或域名
        run: |
          # 创建 .ssh 目录
          mkdir -p /root/.ssh
          chmod 700 /root/.ssh

          # 写入私钥到 id_rsa 文件中
          echo "$SSH_PRIVATE_KEY" > /root/.ssh/id_rsa
          chmod 600 /root/.ssh/id_rsa

          # 自动添加服务器的主机密钥到 known_hosts
          ssh-keyscan -H $SSH_HOST >> /root/.ssh/known_hosts

      # Step 3: 部署到服务器
      - name: Deploy to server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }} # 在 Secrets 中设置的服务器 IP 或域名
        run: |
          ssh root@$SSH_HOST 'cd /root/blog/blog && git pull'
