name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p \~/.ssh
          echo "$SSH_PRIVATE_KEY" > \~/.ssh/id_rsa
          chmod 600 \~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> \~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh root@${{ secrets.SSH_HOST }} 'cd /root/blog/blog && git pull'
